<?php

namespace AppBundle\Repository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends \Doctrine\ORM\EntityRepository implements ContactRepositoryInterface
{

    public function findAllOrderedByFirstName()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM AppBundle:Contact p ORDER BY p.firstname ASC'
            )
            ->getResult();
    }
}
